### ISSUE TITLE
View Bets - Ajout de champs éditables

### ISSUE THREAD

**Issue by AlainBartmanDilaw** [AlainBartmanDilaw/Euro2016Bets#1]
Les 2 zones de score que doit saisir le parieur ne sont pas accessibles dans l'état actuel du dév.

**Comment by Bob11US** [comment]
champs de saisie 
1 les 6 premiers matches n'ont pas de champ ouvert pour saisir les scores
2 si je saisis un score pour le 7ème matche  le fait de valider OK! efface la saisie

**Comment by AlainBartmanDilaw** [comment]
Explication 
1/ J'ai positionné une date bidon afin d'interdire la saisie de scores de matchs "passés"
2/ Je travaille actuellement dessus (JQuery) :(

**Comment by AlainBartmanDilaw** [comment]
Corrigé. 2 champs de score ajoutés.
Reste à mettre en place la màj en base
